package br.com.apresentacao;

import java.util.List;

import javax.swing.event.PopupMenuEvent;

import org.joda.time.DateTime;

import br.com.negocio.NegocioFachada;
import br.com.negocio.entidade.Aeroporto;
import br.com.negocio.enumeracao.Documento;
import br.com.negocio.enumeracao.TipoPassagem;

public class Janela extends javax.swing.JFrame {
	private ComprarAeroportoControlador comprarPassagemControlador;
	private SelecionarDocumentoControlador selecionarDocumentoControlador;
	private SelecionaTipoPassagemControlador selecionaTipoPassagemControlador;

	public Janela() {
		comprarPassagemControlador = new ComprarAeroportoControlador();
		selecionarDocumentoControlador = new SelecionarDocumentoControlador();
		selecionaTipoPassagemControlador = new SelecionaTipoPassagemControlador();
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jTextField1 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jComboBox2 = new javax.swing.JComboBox<>();
		jLabel1 = new javax.swing.JLabel();
		jComboBox4 = new javax.swing.JComboBox<>();
		jLabel4 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox<String>();
		jComboBox3 = new javax.swing.JComboBox<>();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jLabel5.setText("nome:");

		jLabel1.setText("Documento:");

		// lista de documentos
		List<String> listaDocumentos = selecionarDocumentoControlador.getDocumentos();
		for (String item : listaDocumentos) {
			jComboBox2.addItem(item);
		}

		jLabel4.setText("Tipo de passagem:");

		// lista de documentos
		List<String> listaTipoPassagem = selecionaTipoPassagemControlador.getTipoPassagem();
		for (String item : listaTipoPassagem) {
			jComboBox4.addItem(item);
		}

		jLabel3.setText("Destino:");

		jButton1.setText("voltar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel2.setText("Origem:");

		jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
			public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
			}

			public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
			}

			public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
				jComboBox1PopupMenuWillBecomeVisible(evt);
			}
		});
		
		
		jComboBox3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
			public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
			}

			public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
			}

			public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
				jComboBox3PopupMenuWillBecomeVisible(evt);
			}
		});
		

		jButton2.setText("comprar");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel1Layout.createSequentialGroup().addContainerGap()
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																jPanel1Layout.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(jLabel5).addComponent(jLabel4)
																						.addComponent(jLabel1).addComponent(jLabel2)
																						.addComponent(jLabel3)
																						.addGroup(jPanel1Layout.createSequentialGroup()
																								.addComponent(jButton1)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(jButton2)))
																		.addGap(0, 221, Short.MAX_VALUE)))
												.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout
				.createSequentialGroup().addContainerGap().addComponent(jLabel5).addGap(4, 4, 4)
				.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(5, 5, 5).addComponent(jLabel1).addGap(4, 4, 4)
				.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel4)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel2)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel3)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton1).addComponent(jButton2))
				.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout
						.createSequentialGroup().addContainerGap().addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jComboBox1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
		// lista de aeroportos de origem
		List<String> listaOrigem = comprarPassagemControlador.getOrigem();
		for (String item : listaOrigem) {
			jComboBox1.addItem(item);
		}
	}
	
	private void jComboBox3PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
		List<String> listaDestino = comprarPassagemControlador.getDestino(jComboBox1.getSelectedItem().toString());
		// lista de aeroportos de destino
		for (String item : listaDestino) {
			jComboBox3.addItem(item);
		}
	}

	public static void main(String args[]) {
		NegocioFachada fachada = new NegocioFachada();
		fachada.criarBaseDeDados();

		// ** simulando o login no sistema
		fachada.login("lmontgomery0@dmoz.org", "iodl65DoE4ZI");

		// ** simulando uma compra de passagem
		Aeroporto aeroporto = new Aeroporto("1", "teste", "100", "100");
		fachada.comprarPassagem("Pedro", Documento.CPF, TipoPassagem.Estudante, aeroporto, aeroporto, new DateTime());

		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new Janela().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JComboBox<String> jComboBox2;
	private javax.swing.JComboBox<String> jComboBox3;
	private javax.swing.JComboBox<String> jComboBox4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration
}
